# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes  the Euclidean distance between rows of two matrices
#' @param x First matrix
#' @param y Second matrix
#' @return Euclidean distance between rows of \code{x} and \code{y}
#' @export
crossdist <- function(x, y) {
    .Call(`_SLGP_crossdist`, x, y)
}

#' Computes the negative log likelihood
#' @param x First matrix
#' @param y Second matrix
#' @return something
#' @export
negloglike <- function(epsilon, y) {
    .Call(`_SLGP_negloglike`, epsilon, y)
}

